# Generated by Django 5.2.6 on 2025-12-12 11:38

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_title', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CorpusSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('P1', 'P1 - Core'), ('P2', 'P2 - Important'), ('P3', 'P3 - Edge cases')], db_index=True, max_length=10)),
                ('naturaleza', models.CharField(db_index=True, max_length=50)),
                ('area_principal', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('titulo', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('ambito', models.CharField(blank=True, max_length=50, null=True)),
                ('funcion_artisting', models.TextField(blank=True, null=True)),
                ('id_oficial', models.CharField(max_length=100, unique=True)),
                ('url_oficial', models.TextField()),
                ('vigencia', models.TextField(blank=True, null=True)),
                ('nivel_autoridad', models.CharField(blank=True, max_length=50, null=True)),
                ('articulos_clave', models.TextField(blank=True, null=True)),
                ('frecuencia_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting'), ('ingested', 'Ingested'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'legal_corpus_sources',
                'ordering': ['prioridad', 'area_principal', 'titulo'],
                'indexes': [models.Index(fields=['prioridad', 'estado'], name='legal_corpu_priorid_279bec_idx'), models.Index(fields=['naturaleza', 'area_principal'], name='legal_corpu_natural_f41052_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_title', models.TextField()),
                ('doc_id_oficial', models.CharField(max_length=100, unique=True)),
                ('url', models.TextField()),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='legal_graphrag.corpussource')),
            ],
            options={
                'db_table': 'legal_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_type', models.CharField(max_length=50)),
                ('chunk_label', models.TextField(blank=True, null=True)),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='legal_graphrag.legaldocument')),
            ],
            options={
                'db_table': 'legal_document_chunks',
                'ordering': ['document', 'chunk_type'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('feedback_rating', models.IntegerField(blank=True, choices=[(1, 'Bad'), (5, 'Good')], null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='legal_graphrag.chatsession')),
            ],
            options={
                'db_table': 'legal_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='legal_chat__session_226986_idx'), models.Index(fields=['role'], name='legal_chat__role_133a7a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['source'], name='legal_docum_source__bbad16_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['doc_id_oficial'], name='legal_docum_doc_id__f2f0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='legal_docum_documen_f4e995_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_type'], name='legal_docum_chunk_t_5c2238_idx'),
        ),
    ]
